changed test_search_wrong_key_fails to expect a TypeError from unexpected keyword argument (default behaviour) instead of ValueError, which was chosen error from previous implementation of old style kwargs.pop checking